send_email_to:
    - joonas@phz.fi

business_ids:
    active:
        - 1234567-8
        - 0869288-1
    inactive:
        - 2345678-9

useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/44.0.2403.89 Chrome/44.0.2403.89 Safari/537.36
